apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mahesh
  template:
    metadata:
      labels:
        app: mahesh
    spec:
      containers:
        - name: mahesh-dep
          image: maheshchabbi/demoprt1
          ports:
            - containerPort: 80
